name: smart_health_monitoring
description: Smart Health Monitoring & Outbreak Prediction Platform - Mobile App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^3.3.2

  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # HTTP & API
  http: ^1.1.0
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Authentication & Security
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  google_sign_in: ^7.2.0
  local_auth: ^2.1.7
  crypto: ^3.0.3

  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Location & Maps
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.5.0

  # Notifications
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.2
  permission_handler: ^12.0.1

  # Camera & Image
  image_picker: ^1.0.4
  image_cropper: ^10.0.0+1
  cached_network_image: ^3.3.0

  # Utilities
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.1.0
  package_info_plus: ^8.3.1
  url_launcher: ^6.2.2
  share_plus: ^12.0.0
  path_provider: ^2.1.2

  # Charts & Visualization
  fl_chart: ^1.1.1
  syncfusion_flutter_charts: ^31.1.20

  # Form & Validation
  form_builder_validators: ^11.2.0
  flutter_form_builder: ^10.2.0

  # Animation & Effects
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1

  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/icons/
  - assets/animations/
  - assets/translations/
  - assets/fonts/
 
#fonts:
#    - family: Roboto
#     fonts:
#        - asset: assets/fonts/Roboto-Regular.ttf
#        - asset: assets/fonts/Roboto-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Roboto-Bold.ttf
#          weight: 700
